//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoERP.MVC.ServiceGeoCloud {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Binary", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Linq")]
    [System.SerializableAttribute()]
    public partial class Binary : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] BytesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Bytes {
            get {
                return this.BytesField;
            }
            set {
                if ((object.ReferenceEquals(this.BytesField, value) != true)) {
                    this.BytesField = value;
                    this.RaisePropertyChanged("Bytes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceGeoCloud.IServiceGeoCloud")]
    public interface IServiceGeoCloud {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/Test", ReplyAction="http://tempuri.org/IServiceGeoCloud/TestResponse")]
        string Test(string vaseIme);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/UnesiNovuFirmu", ReplyAction="http://tempuri.org/IServiceGeoCloud/UnesiNovuFirmuResponse")]
        void UnesiNovuFirmu(
                    string authcode, 
                    string naziv, 
                    string skraceniNaziv, 
                    string mjesto, 
                    string adresa, 
                    string brTel, 
                    string brMob, 
                    string brFax, 
                    string eMail1, 
                    string eMail2, 
                    string eMail3, 
                    string webAddrs, 
                    string oib, 
                    string mb, 
                    string pdvBr, 
                    string poslovnaBanka, 
                    string brZr, 
                    string direktor, 
                    string iban, 
                    GeoERP.MVC.ServiceGeoCloud.Binary logo, 
                    string korisnickoIme, 
                    string lozinka, 
                    string tipApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/IzmjenaPodatakaFirme", ReplyAction="http://tempuri.org/IServiceGeoCloud/IzmjenaPodatakaFirmeResponse")]
        void IzmjenaPodatakaFirme(
                    string authcode, 
                    int idBanka, 
                    string naziv, 
                    string skraceniNaziv, 
                    string mjesto, 
                    string adresa, 
                    string brTel, 
                    string brMob, 
                    string brFax, 
                    string eMail1, 
                    string eMail2, 
                    string eMail3, 
                    string webAddrs, 
                    string oib, 
                    string mb, 
                    string pdvBr, 
                    string poslovnaBanka, 
                    string brZr, 
                    string direktor, 
                    string iban, 
                    GeoERP.MVC.ServiceGeoCloud.Binary logo, 
                    string korisnickoIme, 
                    string lozinka, 
                    string tipApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/DohvatiFirmu", ReplyAction="http://tempuri.org/IServiceGeoCloud/DohvatiFirmuResponse")]
        string[] DohvatiFirmu(string authcode, int idFirma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/DohvatiBanke", ReplyAction="http://tempuri.org/IServiceGeoCloud/DohvatiBankeResponse")]
        string[] DohvatiBanke(string authcode, int idFirma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/DodajBanku", ReplyAction="http://tempuri.org/IServiceGeoCloud/DodajBankuResponse")]
        void DodajBanku(string authcode, int idFirma, string naziv, string iban, string zr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/IzmjenaPodatakaBanke", ReplyAction="http://tempuri.org/IServiceGeoCloud/IzmjenaPodatakaBankeResponse")]
        void IzmjenaPodatakaBanke(string authcode, int idFirma, int idBanka, string naziv, string iban, string zr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/ObrisiBanku", ReplyAction="http://tempuri.org/IServiceGeoCloud/ObrisiBankuResponse")]
        void ObrisiBanku(string authcode, int idFirma, int idBanka);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/DohvatiPoslove", ReplyAction="http://tempuri.org/IServiceGeoCloud/DohvatiPosloveResponse")]
        string[] DohvatiPoslove(string authcode, int idFirme);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/NoviPosao", ReplyAction="http://tempuri.org/IServiceGeoCloud/NoviPosaoResponse")]
        void NoviPosao(string authcode, int idFirma, int idUser, int redniBroj, string urBroj, string opis, int statusPosla, int status, int olovka, int idVrstaPosla, int idStranke, System.DateTime datumStart, System.DateTime datumEnd, System.DateTime datumOlovka);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/IzmjenaPosla", ReplyAction="http://tempuri.org/IServiceGeoCloud/IzmjenaPoslaResponse")]
        void IzmjenaPosla(string authcode, int idFirma, int idPosao, int idUser, int redniBroj, string urBroj, string opis, int statusPosla, int status, int olovka, int idVrstaPosla, int idStranke, System.DateTime datumStart, System.DateTime datumEnd, System.DateTime datumOlovka);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/ObrisiPosao", ReplyAction="http://tempuri.org/IServiceGeoCloud/ObrisiPosaoResponse")]
        void ObrisiPosao(string authcode, int idFirme, int idPosla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/IzmjenaStatusaPosla", ReplyAction="http://tempuri.org/IServiceGeoCloud/IzmjenaStatusaPoslaResponse")]
        void IzmjenaStatusaPosla(string authcode, int idFirme, int idPosla, int statusPosla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/DodijeliPosao", ReplyAction="http://tempuri.org/IServiceGeoCloud/DodijeliPosaoResponse")]
        void DodijeliPosao(string authcode, int idFirme, int idPosla, int idGrupe, int idRadnik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/IzmjenaDodijeljenogPosla", ReplyAction="http://tempuri.org/IServiceGeoCloud/IzmjenaDodijeljenogPoslaResponse")]
        void IzmjenaDodijeljenogPosla(string authcode, int idFirme, int idDp, int idGrupe, int idRadnik);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/DohvatiZadnjiPosao", ReplyAction="http://tempuri.org/IServiceGeoCloud/DohvatiZadnjiPosaoResponse")]
        string DohvatiZadnjiPosao(string authcode, int idFirme);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/DohvatiZadnjiRedniBrojOdPoslaFirma", ReplyAction="http://tempuri.org/IServiceGeoCloud/DohvatiZadnjiRedniBrojOdPoslaFirmaResponse")]
        int DohvatiZadnjiRedniBrojOdPoslaFirma(string authcode, int idFirme);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/DohvatiGrupe", ReplyAction="http://tempuri.org/IServiceGeoCloud/DohvatiGrupeResponse")]
        string[] DohvatiGrupe(string authcode, int idFirme);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/NovaGrupa", ReplyAction="http://tempuri.org/IServiceGeoCloud/NovaGrupaResponse")]
        void NovaGrupa(string authcode, int idFirme, string naziv, string opis);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/IzmjenaPodatakaGrupe", ReplyAction="http://tempuri.org/IServiceGeoCloud/IzmjenaPodatakaGrupeResponse")]
        void IzmjenaPodatakaGrupe(string authcode, int idFirme, int idGrupe, string naziv, string opis);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/ObrišiGrupu", ReplyAction="http://tempuri.org/IServiceGeoCloud/ObrišiGrupuResponse")]
        void ObrišiGrupu(string authcode, int idFirme, int idGrupe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/DohvatiRadnike", ReplyAction="http://tempuri.org/IServiceGeoCloud/DohvatiRadnikeResponse")]
        string[] DohvatiRadnike(string authcode, int idFirme);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/NoviRadnik", ReplyAction="http://tempuri.org/IServiceGeoCloud/NoviRadnikResponse")]
        void NoviRadnik(string authcode, int idFirme, string ime, string prezime, string oib, string mjesto, string adresa, string brMob, string brTel, string eMail1, string eMail2, string korisnickoIme, string lozinka, int idOvlast, string urBroj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/IzmjenaPodatakaRadnika", ReplyAction="http://tempuri.org/IServiceGeoCloud/IzmjenaPodatakaRadnikaResponse")]
        void IzmjenaPodatakaRadnika(
                    string authcode, 
                    int idFirme, 
                    int idRadnika, 
                    string ime, 
                    string prezime, 
                    string oib, 
                    string mjesto, 
                    string adresa, 
                    string brMob, 
                    string brTel, 
                    string eMail1, 
                    string eMail2, 
                    string korisnickoIme, 
                    string lozinka, 
                    int idOvlast, 
                    string urBroj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/ObrišiRadnika", ReplyAction="http://tempuri.org/IServiceGeoCloud/ObrišiRadnikaResponse")]
        void ObrišiRadnika(string authcode, int idFirme, int idRadnika);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/DohvatiVrstePosla", ReplyAction="http://tempuri.org/IServiceGeoCloud/DohvatiVrstePoslaResponse")]
        string[] DohvatiVrstePosla(string authcode, int idFirma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/NovaVrstaPosla", ReplyAction="http://tempuri.org/IServiceGeoCloud/NovaVrstaPoslaResponse")]
        void NovaVrstaPosla(string authcode, int idFirma, string naziv, string opis);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/IzmjenaVrstaPosla", ReplyAction="http://tempuri.org/IServiceGeoCloud/IzmjenaVrstaPoslaResponse")]
        void IzmjenaVrstaPosla(string authcode, int idFirma, int idVrstaPosla, string naziv, string opis);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/ObrisiVrstaPosla", ReplyAction="http://tempuri.org/IServiceGeoCloud/ObrisiVrstaPoslaResponse")]
        void ObrisiVrstaPosla(string authcode, int idFirma, int idVrstaPosla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/DohvatiMeta", ReplyAction="http://tempuri.org/IServiceGeoCloud/DohvatiMetaResponse")]
        string[] DohvatiMeta(string authcode, int idFirma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/NoviMeta", ReplyAction="http://tempuri.org/IServiceGeoCloud/NoviMetaResponse")]
        void NoviMeta(string authcode, int idFirma, string naziv, int idTipMoguciMeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/IzmjenaMeta", ReplyAction="http://tempuri.org/IServiceGeoCloud/IzmjenaMetaResponse")]
        void IzmjenaMeta(string authcode, int idFirma, int idMeta, string naziv, int idTipMoguciMeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/ObrisiMeta", ReplyAction="http://tempuri.org/IServiceGeoCloud/ObrisiMetaResponse")]
        void ObrisiMeta(string authcode, int idFirma, int idMeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/DohvatiTipoveMeta", ReplyAction="http://tempuri.org/IServiceGeoCloud/DohvatiTipoveMetaResponse")]
        string[] DohvatiTipoveMeta(string authcode, int idFirma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/NoviTipMeta", ReplyAction="http://tempuri.org/IServiceGeoCloud/NoviTipMetaResponse")]
        void NoviTipMeta(string authcode, int idFirma, string naziv, int ovlast);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/IzmjenaTipaMeta", ReplyAction="http://tempuri.org/IServiceGeoCloud/IzmjenaTipaMetaResponse")]
        void IzmjenaTipaMeta(string authcode, int idFirma, int idTipMeta, string naziv, int ovlast);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/ObrisiTipMeta", ReplyAction="http://tempuri.org/IServiceGeoCloud/ObrisiTipMetaResponse")]
        void ObrisiTipMeta(string authcode, int idFirma, int idTipMeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/DohvatiVrijednostMoguciMeta", ReplyAction="http://tempuri.org/IServiceGeoCloud/DohvatiVrijednostMoguciMetaResponse")]
        string[] DohvatiVrijednostMoguciMeta(string authcode, int idFirma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/NovaVrijednostTipMoguciMeta", ReplyAction="http://tempuri.org/IServiceGeoCloud/NovaVrijednostTipMoguciMetaResponse")]
        void NovaVrijednostTipMoguciMeta(string authcode, int idFirma, int idMm, string vrijednost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/IzmjenaVrijednostiTipaMoguciMeta", ReplyAction="http://tempuri.org/IServiceGeoCloud/IzmjenaVrijednostiTipaMoguciMetaResponse")]
        void IzmjenaVrijednostiTipaMoguciMeta(string authcode, int idFirma, int idTipMeta, int idMm, string vrijednost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/ObrisiVrijednostTipMoguciMeta", ReplyAction="http://tempuri.org/IServiceGeoCloud/ObrisiVrijednostTipMoguciMetaResponse")]
        void ObrisiVrijednostTipMoguciMeta(string authcode, int idFirma, int idTipMeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/DodijeliMetaVrstiPosla", ReplyAction="http://tempuri.org/IServiceGeoCloud/DodijeliMetaVrstiPoslaResponse")]
        void DodijeliMetaVrstiPosla(string authcode, int idFirme, int idVrstaPosla, int idMeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/ObrisiMetaVrstiPosla", ReplyAction="http://tempuri.org/IServiceGeoCloud/ObrisiMetaVrstiPoslaResponse")]
        void ObrisiMetaVrstiPosla(string authcode, int idFirme, int idPme);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/UnesiVrijednostiMetaZaPosao", ReplyAction="http://tempuri.org/IServiceGeoCloud/UnesiVrijednostiMetaZaPosaoResponse")]
        void UnesiVrijednostiMetaZaPosao(string authcode, int idFirme, int idPosao, int idMeta, string vrijednostMeta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/ObrisiVrijednostiMetaZaPosao", ReplyAction="http://tempuri.org/IServiceGeoCloud/ObrisiVrijednostiMetaZaPosaoResponse")]
        void ObrisiVrijednostiMetaZaPosao(string authcode, int idFirme, int idPosao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/DohvatiStranke", ReplyAction="http://tempuri.org/IServiceGeoCloud/DohvatiStrankeResponse")]
        string[] DohvatiStranke(string authcode, int idFirma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/DodajStranku", ReplyAction="http://tempuri.org/IServiceGeoCloud/DodajStrankuResponse")]
        void DodajStranku(
                    string authcode, 
                    int idFirma, 
                    string naziv, 
                    string skraceniNaziv, 
                    string mjesto, 
                    string adresa, 
                    string brTel, 
                    string brMob, 
                    string brFax, 
                    string eMail1, 
                    string eMail2, 
                    string eMail3, 
                    string webAdrs, 
                    string oib, 
                    string pdv, 
                    string kontakt, 
                    string banka, 
                    string zrBanke, 
                    int idDjelatnost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/ObrisiStranku", ReplyAction="http://tempuri.org/IServiceGeoCloud/ObrisiStrankuResponse")]
        void ObrisiStranku(string authcode, int idFirme, int idStranke);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/DohvatiDjelatnosti", ReplyAction="http://tempuri.org/IServiceGeoCloud/DohvatiDjelatnostiResponse")]
        string[] DohvatiDjelatnosti(string authcode, int idFirma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/NovaDjelatnost", ReplyAction="http://tempuri.org/IServiceGeoCloud/NovaDjelatnostResponse")]
        void NovaDjelatnost(string authcode, int idFirma, string naziv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/IzmjenaDjelatnosti", ReplyAction="http://tempuri.org/IServiceGeoCloud/IzmjenaDjelatnostiResponse")]
        void IzmjenaDjelatnosti(string authcode, int idFirma, int idDjelatnost, string naziv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/DohvatiPonude", ReplyAction="http://tempuri.org/IServiceGeoCloud/DohvatiPonudeResponse")]
        string[] DohvatiPonude(string authcode, int idFirma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/NovaPonuda", ReplyAction="http://tempuri.org/IServiceGeoCloud/NovaPonudaResponse")]
        void NovaPonuda(string authcode, int idFirmas, int brPonude, int idBanke, string naziv, int idStranka, int idVrstaPosla, string pdv, string ukupanIznos, string rabatPonude, System.DateTime datum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/IzmjenaPonuda", ReplyAction="http://tempuri.org/IServiceGeoCloud/IzmjenaPonudaResponse")]
        void IzmjenaPonuda(string authcode, int idFirmas, int idPonuda, int brPonude, int idBanke, string naziv, int idStranka, int idVrstaPosla, string pdv, string ukupanIznos, string rabatPonude, System.DateTime datum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/ObrisiPonudu", ReplyAction="http://tempuri.org/IServiceGeoCloud/ObrisiPonuduResponse")]
        void ObrisiPonudu(string authcode, int idFirma, int idPonuda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/DohvatiStavke", ReplyAction="http://tempuri.org/IServiceGeoCloud/DohvatiStavkeResponse")]
        string[] DohvatiStavke(string authcode, int idFirma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/NovaStavka", ReplyAction="http://tempuri.org/IServiceGeoCloud/NovaStavkaResponse")]
        void NovaStavka(string authcode, int idFirma, int idPorez, string naziv, string opis, decimal iznosStavke);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/IzmjenaStavka", ReplyAction="http://tempuri.org/IServiceGeoCloud/IzmjenaStavkaResponse")]
        void IzmjenaStavka(string authcode, int idFirma, int idStavke, int idPorez, string naziv, string opis, decimal iznosStavke);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/ObrisiStavku", ReplyAction="http://tempuri.org/IServiceGeoCloud/ObrisiStavkuResponse")]
        void ObrisiStavku(string authCode, int idFirma, int idStavke);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/UnosStavkiPonudeIliRacuna", ReplyAction="http://tempuri.org/IServiceGeoCloud/UnosStavkiPonudeIliRacunaResponse")]
        void UnosStavkiPonudeIliRacuna(string authcode, int idFirma, int idPosao, int idStranke, int brRacuna, int brPonuda, int idStavkaRacuna, string nazivStavke, decimal cijena, decimal iznos, int kolicina, int rabat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/BrisanjeStavkiPonude", ReplyAction="http://tempuri.org/IServiceGeoCloud/BrisanjeStavkiPonudeResponse")]
        void BrisanjeStavkiPonude(string authcode, int idFirma, int brPonuda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/BrisanjeStavkiRacuna", ReplyAction="http://tempuri.org/IServiceGeoCloud/BrisanjeStavkiRacunaResponse")]
        void BrisanjeStavkiRacuna(string authcode, int idFirma, int brRacuna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/DohvatiPoreze", ReplyAction="http://tempuri.org/IServiceGeoCloud/DohvatiPorezeResponse")]
        string[] DohvatiPoreze(string authcode, int idFirma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/NoviPorez", ReplyAction="http://tempuri.org/IServiceGeoCloud/NoviPorezResponse")]
        void NoviPorez(string authcode, int idFirma, long porez);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/IzmjenaPoreza", ReplyAction="http://tempuri.org/IServiceGeoCloud/IzmjenaPorezaResponse")]
        void IzmjenaPoreza(string authcode, int idFirma, int idPorez, long porez);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceGeoCloud/ObrisiPorez", ReplyAction="http://tempuri.org/IServiceGeoCloud/ObrisiPorezResponse")]
        void ObrisiPorez(string authcode, int idFirma, int idPorez);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceGeoCloudChannel : GeoERP.MVC.ServiceGeoCloud.IServiceGeoCloud, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceGeoCloudClient : System.ServiceModel.ClientBase<GeoERP.MVC.ServiceGeoCloud.IServiceGeoCloud>, GeoERP.MVC.ServiceGeoCloud.IServiceGeoCloud {
        
        public ServiceGeoCloudClient() {
        }
        
        public ServiceGeoCloudClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceGeoCloudClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceGeoCloudClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceGeoCloudClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Test(string vaseIme) {
            return base.Channel.Test(vaseIme);
        }
        
        public void UnesiNovuFirmu(
                    string authcode, 
                    string naziv, 
                    string skraceniNaziv, 
                    string mjesto, 
                    string adresa, 
                    string brTel, 
                    string brMob, 
                    string brFax, 
                    string eMail1, 
                    string eMail2, 
                    string eMail3, 
                    string webAddrs, 
                    string oib, 
                    string mb, 
                    string pdvBr, 
                    string poslovnaBanka, 
                    string brZr, 
                    string direktor, 
                    string iban, 
                    GeoERP.MVC.ServiceGeoCloud.Binary logo, 
                    string korisnickoIme, 
                    string lozinka, 
                    string tipApp) {
            base.Channel.UnesiNovuFirmu(authcode, naziv, skraceniNaziv, mjesto, adresa, brTel, brMob, brFax, eMail1, eMail2, eMail3, webAddrs, oib, mb, pdvBr, poslovnaBanka, brZr, direktor, iban, logo, korisnickoIme, lozinka, tipApp);
        }
        
        public void IzmjenaPodatakaFirme(
                    string authcode, 
                    int idBanka, 
                    string naziv, 
                    string skraceniNaziv, 
                    string mjesto, 
                    string adresa, 
                    string brTel, 
                    string brMob, 
                    string brFax, 
                    string eMail1, 
                    string eMail2, 
                    string eMail3, 
                    string webAddrs, 
                    string oib, 
                    string mb, 
                    string pdvBr, 
                    string poslovnaBanka, 
                    string brZr, 
                    string direktor, 
                    string iban, 
                    GeoERP.MVC.ServiceGeoCloud.Binary logo, 
                    string korisnickoIme, 
                    string lozinka, 
                    string tipApp) {
            base.Channel.IzmjenaPodatakaFirme(authcode, idBanka, naziv, skraceniNaziv, mjesto, adresa, brTel, brMob, brFax, eMail1, eMail2, eMail3, webAddrs, oib, mb, pdvBr, poslovnaBanka, brZr, direktor, iban, logo, korisnickoIme, lozinka, tipApp);
        }
        
        public string[] DohvatiFirmu(string authcode, int idFirma) {
            return base.Channel.DohvatiFirmu(authcode, idFirma);
        }
        
        public string[] DohvatiBanke(string authcode, int idFirma) {
            return base.Channel.DohvatiBanke(authcode, idFirma);
        }
        
        public void DodajBanku(string authcode, int idFirma, string naziv, string iban, string zr) {
            base.Channel.DodajBanku(authcode, idFirma, naziv, iban, zr);
        }
        
        public void IzmjenaPodatakaBanke(string authcode, int idFirma, int idBanka, string naziv, string iban, string zr) {
            base.Channel.IzmjenaPodatakaBanke(authcode, idFirma, idBanka, naziv, iban, zr);
        }
        
        public void ObrisiBanku(string authcode, int idFirma, int idBanka) {
            base.Channel.ObrisiBanku(authcode, idFirma, idBanka);
        }
        
        public string[] DohvatiPoslove(string authcode, int idFirme) {
            return base.Channel.DohvatiPoslove(authcode, idFirme);
        }
        
        public void NoviPosao(string authcode, int idFirma, int idUser, int redniBroj, string urBroj, string opis, int statusPosla, int status, int olovka, int idVrstaPosla, int idStranke, System.DateTime datumStart, System.DateTime datumEnd, System.DateTime datumOlovka) {
            base.Channel.NoviPosao(authcode, idFirma, idUser, redniBroj, urBroj, opis, statusPosla, status, olovka, idVrstaPosla, idStranke, datumStart, datumEnd, datumOlovka);
        }
        
        public void IzmjenaPosla(string authcode, int idFirma, int idPosao, int idUser, int redniBroj, string urBroj, string opis, int statusPosla, int status, int olovka, int idVrstaPosla, int idStranke, System.DateTime datumStart, System.DateTime datumEnd, System.DateTime datumOlovka) {
            base.Channel.IzmjenaPosla(authcode, idFirma, idPosao, idUser, redniBroj, urBroj, opis, statusPosla, status, olovka, idVrstaPosla, idStranke, datumStart, datumEnd, datumOlovka);
        }
        
        public void ObrisiPosao(string authcode, int idFirme, int idPosla) {
            base.Channel.ObrisiPosao(authcode, idFirme, idPosla);
        }
        
        public void IzmjenaStatusaPosla(string authcode, int idFirme, int idPosla, int statusPosla) {
            base.Channel.IzmjenaStatusaPosla(authcode, idFirme, idPosla, statusPosla);
        }
        
        public void DodijeliPosao(string authcode, int idFirme, int idPosla, int idGrupe, int idRadnik) {
            base.Channel.DodijeliPosao(authcode, idFirme, idPosla, idGrupe, idRadnik);
        }
        
        public void IzmjenaDodijeljenogPosla(string authcode, int idFirme, int idDp, int idGrupe, int idRadnik) {
            base.Channel.IzmjenaDodijeljenogPosla(authcode, idFirme, idDp, idGrupe, idRadnik);
        }
        
        public string DohvatiZadnjiPosao(string authcode, int idFirme) {
            return base.Channel.DohvatiZadnjiPosao(authcode, idFirme);
        }
        
        public int DohvatiZadnjiRedniBrojOdPoslaFirma(string authcode, int idFirme) {
            return base.Channel.DohvatiZadnjiRedniBrojOdPoslaFirma(authcode, idFirme);
        }
        
        public string[] DohvatiGrupe(string authcode, int idFirme) {
            return base.Channel.DohvatiGrupe(authcode, idFirme);
        }
        
        public void NovaGrupa(string authcode, int idFirme, string naziv, string opis) {
            base.Channel.NovaGrupa(authcode, idFirme, naziv, opis);
        }
        
        public void IzmjenaPodatakaGrupe(string authcode, int idFirme, int idGrupe, string naziv, string opis) {
            base.Channel.IzmjenaPodatakaGrupe(authcode, idFirme, idGrupe, naziv, opis);
        }
        
        public void ObrišiGrupu(string authcode, int idFirme, int idGrupe) {
            base.Channel.ObrišiGrupu(authcode, idFirme, idGrupe);
        }
        
        public string[] DohvatiRadnike(string authcode, int idFirme) {
            return base.Channel.DohvatiRadnike(authcode, idFirme);
        }
        
        public void NoviRadnik(string authcode, int idFirme, string ime, string prezime, string oib, string mjesto, string adresa, string brMob, string brTel, string eMail1, string eMail2, string korisnickoIme, string lozinka, int idOvlast, string urBroj) {
            base.Channel.NoviRadnik(authcode, idFirme, ime, prezime, oib, mjesto, adresa, brMob, brTel, eMail1, eMail2, korisnickoIme, lozinka, idOvlast, urBroj);
        }
        
        public void IzmjenaPodatakaRadnika(
                    string authcode, 
                    int idFirme, 
                    int idRadnika, 
                    string ime, 
                    string prezime, 
                    string oib, 
                    string mjesto, 
                    string adresa, 
                    string brMob, 
                    string brTel, 
                    string eMail1, 
                    string eMail2, 
                    string korisnickoIme, 
                    string lozinka, 
                    int idOvlast, 
                    string urBroj) {
            base.Channel.IzmjenaPodatakaRadnika(authcode, idFirme, idRadnika, ime, prezime, oib, mjesto, adresa, brMob, brTel, eMail1, eMail2, korisnickoIme, lozinka, idOvlast, urBroj);
        }
        
        public void ObrišiRadnika(string authcode, int idFirme, int idRadnika) {
            base.Channel.ObrišiRadnika(authcode, idFirme, idRadnika);
        }
        
        public string[] DohvatiVrstePosla(string authcode, int idFirma) {
            return base.Channel.DohvatiVrstePosla(authcode, idFirma);
        }
        
        public void NovaVrstaPosla(string authcode, int idFirma, string naziv, string opis) {
            base.Channel.NovaVrstaPosla(authcode, idFirma, naziv, opis);
        }
        
        public void IzmjenaVrstaPosla(string authcode, int idFirma, int idVrstaPosla, string naziv, string opis) {
            base.Channel.IzmjenaVrstaPosla(authcode, idFirma, idVrstaPosla, naziv, opis);
        }
        
        public void ObrisiVrstaPosla(string authcode, int idFirma, int idVrstaPosla) {
            base.Channel.ObrisiVrstaPosla(authcode, idFirma, idVrstaPosla);
        }
        
        public string[] DohvatiMeta(string authcode, int idFirma) {
            return base.Channel.DohvatiMeta(authcode, idFirma);
        }
        
        public void NoviMeta(string authcode, int idFirma, string naziv, int idTipMoguciMeta) {
            base.Channel.NoviMeta(authcode, idFirma, naziv, idTipMoguciMeta);
        }
        
        public void IzmjenaMeta(string authcode, int idFirma, int idMeta, string naziv, int idTipMoguciMeta) {
            base.Channel.IzmjenaMeta(authcode, idFirma, idMeta, naziv, idTipMoguciMeta);
        }
        
        public void ObrisiMeta(string authcode, int idFirma, int idMeta) {
            base.Channel.ObrisiMeta(authcode, idFirma, idMeta);
        }
        
        public string[] DohvatiTipoveMeta(string authcode, int idFirma) {
            return base.Channel.DohvatiTipoveMeta(authcode, idFirma);
        }
        
        public void NoviTipMeta(string authcode, int idFirma, string naziv, int ovlast) {
            base.Channel.NoviTipMeta(authcode, idFirma, naziv, ovlast);
        }
        
        public void IzmjenaTipaMeta(string authcode, int idFirma, int idTipMeta, string naziv, int ovlast) {
            base.Channel.IzmjenaTipaMeta(authcode, idFirma, idTipMeta, naziv, ovlast);
        }
        
        public void ObrisiTipMeta(string authcode, int idFirma, int idTipMeta) {
            base.Channel.ObrisiTipMeta(authcode, idFirma, idTipMeta);
        }
        
        public string[] DohvatiVrijednostMoguciMeta(string authcode, int idFirma) {
            return base.Channel.DohvatiVrijednostMoguciMeta(authcode, idFirma);
        }
        
        public void NovaVrijednostTipMoguciMeta(string authcode, int idFirma, int idMm, string vrijednost) {
            base.Channel.NovaVrijednostTipMoguciMeta(authcode, idFirma, idMm, vrijednost);
        }
        
        public void IzmjenaVrijednostiTipaMoguciMeta(string authcode, int idFirma, int idTipMeta, int idMm, string vrijednost) {
            base.Channel.IzmjenaVrijednostiTipaMoguciMeta(authcode, idFirma, idTipMeta, idMm, vrijednost);
        }
        
        public void ObrisiVrijednostTipMoguciMeta(string authcode, int idFirma, int idTipMeta) {
            base.Channel.ObrisiVrijednostTipMoguciMeta(authcode, idFirma, idTipMeta);
        }
        
        public void DodijeliMetaVrstiPosla(string authcode, int idFirme, int idVrstaPosla, int idMeta) {
            base.Channel.DodijeliMetaVrstiPosla(authcode, idFirme, idVrstaPosla, idMeta);
        }
        
        public void ObrisiMetaVrstiPosla(string authcode, int idFirme, int idPme) {
            base.Channel.ObrisiMetaVrstiPosla(authcode, idFirme, idPme);
        }
        
        public void UnesiVrijednostiMetaZaPosao(string authcode, int idFirme, int idPosao, int idMeta, string vrijednostMeta) {
            base.Channel.UnesiVrijednostiMetaZaPosao(authcode, idFirme, idPosao, idMeta, vrijednostMeta);
        }
        
        public void ObrisiVrijednostiMetaZaPosao(string authcode, int idFirme, int idPosao) {
            base.Channel.ObrisiVrijednostiMetaZaPosao(authcode, idFirme, idPosao);
        }
        
        public string[] DohvatiStranke(string authcode, int idFirma) {
            return base.Channel.DohvatiStranke(authcode, idFirma);
        }
        
        public void DodajStranku(
                    string authcode, 
                    int idFirma, 
                    string naziv, 
                    string skraceniNaziv, 
                    string mjesto, 
                    string adresa, 
                    string brTel, 
                    string brMob, 
                    string brFax, 
                    string eMail1, 
                    string eMail2, 
                    string eMail3, 
                    string webAdrs, 
                    string oib, 
                    string pdv, 
                    string kontakt, 
                    string banka, 
                    string zrBanke, 
                    int idDjelatnost) {
            base.Channel.DodajStranku(authcode, idFirma, naziv, skraceniNaziv, mjesto, adresa, brTel, brMob, brFax, eMail1, eMail2, eMail3, webAdrs, oib, pdv, kontakt, banka, zrBanke, idDjelatnost);
        }
        
        public void ObrisiStranku(string authcode, int idFirme, int idStranke) {
            base.Channel.ObrisiStranku(authcode, idFirme, idStranke);
        }
        
        public string[] DohvatiDjelatnosti(string authcode, int idFirma) {
            return base.Channel.DohvatiDjelatnosti(authcode, idFirma);
        }
        
        public void NovaDjelatnost(string authcode, int idFirma, string naziv) {
            base.Channel.NovaDjelatnost(authcode, idFirma, naziv);
        }
        
        public void IzmjenaDjelatnosti(string authcode, int idFirma, int idDjelatnost, string naziv) {
            base.Channel.IzmjenaDjelatnosti(authcode, idFirma, idDjelatnost, naziv);
        }
        
        public string[] DohvatiPonude(string authcode, int idFirma) {
            return base.Channel.DohvatiPonude(authcode, idFirma);
        }
        
        public void NovaPonuda(string authcode, int idFirmas, int brPonude, int idBanke, string naziv, int idStranka, int idVrstaPosla, string pdv, string ukupanIznos, string rabatPonude, System.DateTime datum) {
            base.Channel.NovaPonuda(authcode, idFirmas, brPonude, idBanke, naziv, idStranka, idVrstaPosla, pdv, ukupanIznos, rabatPonude, datum);
        }
        
        public void IzmjenaPonuda(string authcode, int idFirmas, int idPonuda, int brPonude, int idBanke, string naziv, int idStranka, int idVrstaPosla, string pdv, string ukupanIznos, string rabatPonude, System.DateTime datum) {
            base.Channel.IzmjenaPonuda(authcode, idFirmas, idPonuda, brPonude, idBanke, naziv, idStranka, idVrstaPosla, pdv, ukupanIznos, rabatPonude, datum);
        }
        
        public void ObrisiPonudu(string authcode, int idFirma, int idPonuda) {
            base.Channel.ObrisiPonudu(authcode, idFirma, idPonuda);
        }
        
        public string[] DohvatiStavke(string authcode, int idFirma) {
            return base.Channel.DohvatiStavke(authcode, idFirma);
        }
        
        public void NovaStavka(string authcode, int idFirma, int idPorez, string naziv, string opis, decimal iznosStavke) {
            base.Channel.NovaStavka(authcode, idFirma, idPorez, naziv, opis, iznosStavke);
        }
        
        public void IzmjenaStavka(string authcode, int idFirma, int idStavke, int idPorez, string naziv, string opis, decimal iznosStavke) {
            base.Channel.IzmjenaStavka(authcode, idFirma, idStavke, idPorez, naziv, opis, iznosStavke);
        }
        
        public void ObrisiStavku(string authCode, int idFirma, int idStavke) {
            base.Channel.ObrisiStavku(authCode, idFirma, idStavke);
        }
        
        public void UnosStavkiPonudeIliRacuna(string authcode, int idFirma, int idPosao, int idStranke, int brRacuna, int brPonuda, int idStavkaRacuna, string nazivStavke, decimal cijena, decimal iznos, int kolicina, int rabat) {
            base.Channel.UnosStavkiPonudeIliRacuna(authcode, idFirma, idPosao, idStranke, brRacuna, brPonuda, idStavkaRacuna, nazivStavke, cijena, iznos, kolicina, rabat);
        }
        
        public void BrisanjeStavkiPonude(string authcode, int idFirma, int brPonuda) {
            base.Channel.BrisanjeStavkiPonude(authcode, idFirma, brPonuda);
        }
        
        public void BrisanjeStavkiRacuna(string authcode, int idFirma, int brRacuna) {
            base.Channel.BrisanjeStavkiRacuna(authcode, idFirma, brRacuna);
        }
        
        public string[] DohvatiPoreze(string authcode, int idFirma) {
            return base.Channel.DohvatiPoreze(authcode, idFirma);
        }
        
        public void NoviPorez(string authcode, int idFirma, long porez) {
            base.Channel.NoviPorez(authcode, idFirma, porez);
        }
        
        public void IzmjenaPoreza(string authcode, int idFirma, int idPorez, long porez) {
            base.Channel.IzmjenaPoreza(authcode, idFirma, idPorez, porez);
        }
        
        public void ObrisiPorez(string authcode, int idFirma, int idPorez) {
            base.Channel.ObrisiPorez(authcode, idFirma, idPorez);
        }
    }
}
